name: arcface-tf2.4
channels:
  - conda-forge

dependencies:
  - python==3.7
  - pip
  - pip:
    - tensorflow-gpu==2.4.0
    - opencv-python==4.1.1.26
    - bcolz==1.2.0
    - sklearn2
    - PyYAML
    - tqdm
